{{- if include "mongo-compass.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-compass.secretName" . }}
  labels:
    {{- include "mongo-compass.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.auth.sessionSecret }}
  session-secret: {{ .Values.auth.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.auth.basic.password }}
  basic-auth-password: {{ .Values.auth.basic.password | quote }}
  {{- end }}
  {{- if .Values.genAI.openaiApiKey }}
  openai-api-key: {{ .Values.genAI.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.editConnections.masterPassword }}
  master-password: {{ .Values.editConnections.masterPassword | quote }}
  {{- end }}
{{- end }}
