apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-compass.fullname" . }}
  labels:
    {{- include "mongo-compass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "mongo-compass.servicePort" . }}
      targetPort: {{ if .Values.oauth2Proxy.enabled }}oauth2-proxy{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-compass.selectorLabels" . | nindent 4 }}
